.TH AUX2BIB 1

.SH NAME
AUX2BIB \- Extracts a BibTeX database according to an aux file.

.SH SYNOPSIS
.B aux2bib <auxfile>


.SH DESCRIPTION

Aux2bib reads a \fI.aux\fR file as produced by \fBLaTeX\fR and writes
to standard output a bibtex file containing exactly the bibtex entries
refereed in the aux file. 

.SH SEE ALSO
.BR bibtex (1),
.BR latex (1),
.br
.I http://www.lri.fr/~filliatr/bibtex2html/
.br
.I /usr/share/doc/bibtex2html

.SH AUTHOR
Ralf Treinen <treinen@debian.org>
